services:
  l8testudy:
    # Tausche 'DEIN_USER' mit deinem GitHub-Namen aus. 
    # Wenn dein Repo privat ist, musst du evtl. einen Token nutzen oder das Image anders bauen.
    build: https://github.com/L8teNever/L8teStudy.git#main
    container_name: l8testudy
    ports:
      - "5000:5000"
    volumes:
      # Daten werden im Ordner gespeichert, wo diese Datei ausgef√ºhrt wird
      - ./data:/data
      - ./uploads:/app/static/uploads
    environment:
      - DATABASE_URL=sqlite:////data/l8testudy.db
      - SECRET_KEY=aender_mich_in_was_sicheres
    restart: always
