services:
  l8testudy:
    image: l8tenever/l8testudy:latest
    container_name: l8testudy_local
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/data
      - ./static/uploads:/data/uploads
    environment:
      - DATABASE_URL=sqlite:////data/l8testudy.db
      - SECRET_KEY=local-dev-secret-key
      - UPLOAD_FOLDER=/data/uploads
    restart: always
